project:
  type: website
  output-dir: docs
execute:
  freeze: auto
format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom-dark.scss]
    include-in-header: "scripts/translate.html"
website:
  title: "We Data"
  description: "We Data website"
  favicon: "images/me.png"
  google-analytics: "G-ECFW8LLBS7"
  twitter-card:
    creator: "@munoztd0"
  site-url: https://we-data.ch/
  repo-actions: [edit, issue]
  navbar:
    title: false
    logo: "images/primary.png"
    background: primary
    search: true
    left:
      - text: "{{< fa house-user >}} Home"
        href: index.qmd
      - text: "{{< fa laptop-code >}} Blog"
        href: blog.qmd
      - text: "{{< fa briefcase >}} Services"
        href: services/index.qmd
      # - text: "{{< fa chalkboard-user >}} Talks"
      #   href: talks.qmd
      # - text: "{{< fa chart-line >}} Projects"
      #   href: projects.qmd
      # team members
      - text: "{{< fa book >}} Exercises"
        href: https://we-data-ch.github.io/wedata-ultimate-r-exercises/
      - text: "{{< fa users >}} Team"
        href: team.qmd
      - text: "{{< fa code >}} Projects"
        href: projects.qmd
      - text: "{{< fa calendar >}} Activities"
        href: activities.qmd
      - text: "{{< fa address-card >}} About"
        href: about.qmd
      # - text: "{{< fa paperclip >}} Vitae"
      #   href: https://github.com/munoztd0/CV_DMT/raw/main/CV_DMT.pdf
      - text: "{{< fa paper-plane >}} Contact"
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/we-data-ch
      - icon: youtube
        href: https://www.youtube.com/@wedata_unige
      - icon: twitter
        href: https://twitter.com/wedata_unige
      - icon: linkedin
        href: https://www.linkedin.com/company/wedata-gen%C3%A8ve/
  page-footer:
    background: primary
    left: "{{< fa copyright >}} 2024, David Munoz Tord"
    center:
      - text: "<img src='/images/primary.png' width='auto' height='30px'>"
    right:
      - icon: github
        href: https://github.com/we-data-ch
      - icon: youtube
        href: https://www.youtube.com/@wedata_unige
      - icon: twitter
        href: https://twitter.com/wedata_unige
      - icon: linkedin
        href: https://www.linkedin.com/company/wedata-gen%C3%A8ve/




